### PR TITLE
Fix for issue #6 now spaces in lastname are allowed

### LINKED ISSUE #6: Geen spaties in achternaam mogelijk
Het is momenteel niet mogelijk voor iemand die als achternaam heeft: 'Olde Agterhuis', 'Olde Scholtenhuis', enz.. het formulier in te vullen, daar spaties in achternamen niet toegestaan zijn.

### PR DESCRIPTION
**Pull request by frenck**
Small fix allowing spaces to be used in field 'achternaam'. This because there are a lot of people who do have more than one word in their lastname. (e.g. 'Olde Scholtenhuis')

Closes #6

### CODE REVIEW

**Comment by GeertJohan** [comment]
Auch.. heb ik die gemist..

**Comment by GeertJohan** [comment]
Stom...

Hoe dan ook, fix staat nu ook live.

**Comment by MichielVdAnker** [comment]
Thanks a lot @frenck , I thought people would be accustomed to use a "-" in those cases, but this is way better.

**Comment by frenck** [comment]
No problem, actually, I must thank you guys for making all this possible. Great job!

**Pull request merged**
