### PR TITLE
Fixes issue #10 forcing the 'huisnummer' field to start with a number

### PR DESCRIPTION
**Pull request by frenck**
Implements a small change to the 'huisnummer' field to force them to start with a number.

As suggested in issue #10

### CODE REVIEW

**Comment by GeertJohan** [comment]
Extremely late reply, sorry. Thanks for the improvement!

**Comment by GeertJohan** [comment]
Had to manually merge the change.

**Comment by frenck** [comment]
@GeertJohan About 250 days late reply... As shown by the counter on geenstijl.nl 😂

**Comment by GeertJohan** [comment]
Haha, well better late then never.
Are you perchance interested in joining the new GeenPeil project? @frenck

**Comment by frenck** [comment]
@GeertJohan Send me a message privately and we'll check. (my username @ gmail.com)

**Pull request closed without merging**
